---
# tasks file for auto upgrade target server driver&firmware

# deploy houp repo to target server
- import_tasks: add-repo.yml

- name: "Auto Upgrade Huawei Server"
  shell: /bin/sh {{ hsu_root }}/bin/hsu auto-upgrade 
   {{ drivers | default([]) | plain}} 
   {{ inbandFW | default([]) | plain}} 
   {{ outbandFW | default([]) | plain}} 
   --format=json
  register: result
  changed_when: False

- name: "Auto Upgrade Huawei Server Result"
  debug: msg="{{ result.stdout | hsu }}"
  notify: Remove Huawei Server Upgrade Tool
  