---
# tasks file for listing target server driver versions

- import_tasks: add-repo.yml

- name: "Gather Huawei Server Driver versions"
  shell: "/bin/sh {{ hsu_root }}/bin/hsu verify --format=json"
  register: result
  changed_when: False

- name: "Display Huawei Server Driver versions"
  debug: msg="{{ result.stdout | hsu }}"
