---
# tasks file for huawei.ibmc

# deploy houp repo to target server
- import_tasks: add_repo.yml

# deploy HSU distribution to target server
- import_tasks: deploy.yml

# Dynamic include a task base on command
- include_tasks: "{{command}}.yml"
