---
# tasks file for huawei.ibmc

# deploy HSU distribution to target server
- import_tasks: deploy.yml

# Run get version task only when get-version tag specified
# Get target server driver versions
- import_tasks: {{command}}.yml


