---
  # tasks file for query server driver upgrade progress

- name: "Check required variables for upgrade driver task"
  fail: msg="Variable 'taskid' is not defined"
  when: item not in vars
  with_items:
    - taskid
    
- name: "Trace Huawei Server Driver upgrade progress"
  shell: "/bin/sh {{ hsu_root }}/bin/hsu progress {{ taskid }} --format=json"
  register: result
  changed_when: False

- name: "Trace Huawei Server Driver upgrade progress Result"
  debug: msg="{{ result.stdout | hsu }}"
