---
# tasks file for Upgrade target server driver version

- import_tasks: add-repo.yml

# - name: "Check required variables for upgrade driver task"
#   fail: msg="Variable '{{ item }}' is not defined"
#   when: item not in vars
#   with_items:
#     - driver
#     - version

- name: "Upgrade Huawei Server Driver"
  shell: "/bin/sh {{ hsu_root }}/bin/hsu verify && /bin/sh {{ hsu_root }}/bin/hsu upgrade {{ drivers | plain}} --format=json"
  register: result
  changed_when: False

- name: "Upgrade Huawei Server Driver Result"
  debug: msg="{{ result.stdout | hsu }}"
  