---
# test tasks file for how to auto upgrade all drivers and firmwares
  
- hosts: servers
  remote_user: root
  roles:
    - role: 'IamFive.server_upgrade'
      command: 'auto-upgrade'
      # optional, default huawei houp repo
      # driver_repo_baseurl: http://houp.huawei.com/download/server/Linux/Driver/Redhat/Rhel7.4/$basearch/current/
      # optional, default no
      # driver_repo_gpgcheck: yes
      # optional, default huawei houp firmware repo 
      # firmware_repo_baseurl: http://houp.huawei.com/download/server/Linux/firmware/current/