---
# test tasks file for how to upgrade inband

- hosts: servers
  remote_user: root
  roles:
    - role: 'IamFive.server_upgrade'
      command: 'auto-upgrade'
      # the driver list to be upgraded
      drivers: 
        - ['raid', '0.0.013']
        # - ['driver1', 'driver1-version']
        # - ['driver2', 'driver2-version']
      inbandFW:
        - ['firmware1', 'version1']
        # - ['firmware2', 'version2']
      # optional, default huawei houp repo
      # because houp repo is not ready for CentOS, we use rhel instead for testing
      # driver_repo_baseurl: http://houp.huawei.com/download/server/Linux/Driver/Redhat/Rhel7.4/$basearch/current/
      # optional, default no
      # driver_repo_gpgcheck: yes
      # optional, default huawei houp firmware repo 
      # firmware_repo_baseurl: http://houp.huawei.com/download/server/Linux/firmware/current/